# Generated by Django 4.0.4 on 2022-05-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField(verbose_name='Appointment URL')),
                ('patient_id', models.CharField(max_length=10, verbose_name='Patient ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Amount')),
                ('note', models.TextField(max_length=5000, verbose_name='Note')),
                ('appointment_sr_no', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='Appointment ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('length', models.TimeField(verbose_name='Duration')),
                ('description', models.TextField(max_length=5000, verbose_name='Description')),
                ('appointment_made_date', models.DateTimeField(verbose_name='Appoinment Made On')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Patients Name')),
                ('patient_href', models.URLField(verbose_name='Patients URL')),
            ],
        ),
    ]
